# fly.toml app configuration file generated for abbot-engelborg on 2023-07-04T15:37:48-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "abbot-engelborg"
primary_region = "cdg"
