on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  contrib-readme-job:
    runs-on: ubuntu-latest
    name: Contributors-Readme-Action
    steps:
      - name: Contributors List
        uses: akhilmhdh/contributors-readme-action@v2.2
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          commit_message: Updated contributors list
